const bookRoute = require("./book.route");
const bookCategoryRoute = require("./book-category.route");
const authorRoute = require("./author.route");
const publisherRoute = require("./publisher.route");
const paymentMethodRoute = require("./payment-method.route");
const carrierRoute = require("./carrier.route");
const blogRoute = require("./blog.route");
const roleRoute = require("./role.route");
const distributorRoute = require("./distributor.route");
const coverTypeRoute = require("./cover-type.route");
const accountRoute = require("./account.route");
const myAccountRoute = require("./my-account.route");
const orderRoute = require("./order.route");
const authRoute = require("./auth.route");
const authMiddleware = require("../../middlewares/admin/auth.middleware");

module.exports = (app) => {
    app.use("/api/v1/admin/books", authMiddleware.verifyToken, authMiddleware.verifyRole, bookRoute);
    app.use("/api/v1/admin/book-categories", authMiddleware.verifyToken, authMiddleware.verifyRole, bookCategoryRoute);
    app.use("/api/v1/admin/authors", authMiddleware.verifyToken, authMiddleware.verifyRole, authorRoute);
    app.use("/api/v1/admin/publishers", authMiddleware.verifyToken, authMiddleware.verifyRole, publisherRoute);
    app.use("/api/v1/admin/payment-methods", authMiddleware.verifyToken, authMiddleware.verifyRole, paymentMethodRoute);
    app.use("/api/v1/admin/carriers", authMiddleware.verifyToken, authMiddleware.verifyRole, carrierRoute);
    app.use("/api/v1/admin/blogs", authMiddleware.verifyToken, authMiddleware.verifyRole, blogRoute);
    app.use("/api/v1/admin/roles", authMiddleware.verifyToken, authMiddleware.verifyRole, roleRoute);
    app.use("/api/v1/admin/distributors", authMiddleware.verifyToken, authMiddleware.verifyRole, distributorRoute);
    app.use("/api/v1/admin/cover-types", authMiddleware.verifyToken, authMiddleware.verifyRole, coverTypeRoute);
    app.use("/api/v1/admin/accounts", authMiddleware.verifyToken, authMiddleware.verifyRole, accountRoute);
    app.use("/api/v1/admin/my-account", authMiddleware.verifyToken, myAccountRoute);
    app.use("/api/v1/admin/orders", authMiddleware.verifyToken, authMiddleware.verifyRole, orderRoute);
    app.use("/api/v1/admin/auth", authRoute);
};